MVC/MVC/Models/ErrorViewModel.cs
using System;

namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/MVC/Models/Event.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Models
{

    public class Event
    {
        [Key]
        [Required]
        public string Title { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime Date { get; set; }
        [Required]
        public string Location { get; set; }
        [Required]
       
        public int StartTime { get; set; }
        [Required]
        public string Type { get; set; }
        public int Duration { get; set; }
        public string Description { get; set; }
        public string OtherDetails { get; set; }
        public string Invite { get; set; }

        public string Userid { get; set; }

    }
}

MVC/MVC/Models/Register.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Models
{
    public class Register
    {
        
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Passwords don't match")]
        public string ConfirmPassword { get; set; }


    }
}

MVC/MVC/Models/SignInModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Models
{
    public class SignInModel
    {
        [Required, EmailAddress]
        public string Email { get; set; }

        
        [Required, DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

MVC/MVC/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVC.Models;
using MVC.Repository;

namespace MVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IAccountRepository _accountRepository;

        public AccountController(IAccountRepository accountRepository)
        {
            _accountRepository = accountRepository;
        }
        [Route("register")]
        public IActionResult Register()
        {
            return View();
        }

        [Route("register")]
        [HttpPost]
        public async Task<IActionResult> Register(Register userModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _accountRepository.CreateUserAsync(userModel);

                if (!result.Succeeded)
                {
                    foreach (var errorMessage in result.Errors)
                    {
                        ModelState.AddModelError("", errorMessage.Description);
                    }

                    return View(userModel);
                }

                ModelState.Clear();
            }
            return View();
        }

        [Route("login")]
        public IActionResult Login()
        {
            return View();
        }

        [Route("login")]
        [HttpPost]
        public async Task<IActionResult> Login(SignInModel signInModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _accountRepository.PasswordSignInAsync(signInModel);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index", "Home");
                }
                ModelState.AddModelError("", "invalid credentials");
            }
            return View();
        }

        [Route("logout")]
        public async Task<IActionResult> Logout()
        {
            await _accountRepository.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

MVC/MVC/Controllers/EventController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVC.Data;
using MVC.Models;
using System.Net;

namespace MVC.Controllers
{
    public class EventController : Controller
    {
        private readonly ApplicationDbContext _db;

        public EventController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Event> objList = _db.Events;
            return View(objList);
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // post - create

        [HttpPost]

        public IActionResult Create(Event obj)
        {
            
                _db.Events.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            

        }
        //public ActionResult Details(string title)
        //{
        //    if (title == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Event obj = _db.Events.Find(title);
        //    if (obj == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(obj);
        //}

        //private ActionResult HttpNotFound()
        //{
        //    throw new NotImplementedException();
        //}

        public IActionResult Details(string title)
        {
            if (title == null)
            {
                return NotFound();
            }
            var obj = _db.Events.Find(title);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        [Authorize]
        // get -update
        public IActionResult Update(string title)
        {
            if (title == null)
            {
                return NotFound();
            }
            var obj = _db.Events.Find(title);

            if (obj == null)
            {
                return NotFound();
            }

            return View(obj);
        }

        //post-update


        [HttpPost]

        public IActionResult Update(Event obj)
        {
            _db.Events.Update(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC/MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using MVC.Data;
using MVC.Models;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        //private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _db;


        // public HomeController(ILogger<HomeController> logger)
        //{
        //  _logger = logger;
        //}
        public HomeController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<Event> objList = _db.Events;
            return View(objList);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [Route("Customer-Support")]
        public RedirectResult CustomerSupport()
        {
            return Redirect("https://www.nagarro.com/en/contact-us");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/MVC/Views/Event/Create.cshtml
@model MVC.Models.Event

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Event </h2>
        </div>
        <div class="row">
            <!--<div class="col-6">-->
            <div class="form-group col-4">
                <div class="row-4 mb-2">
                    <label asp-for="Title"></label>
                </div>
            </div>
            <div class="form-group col-8">
                <div class=" row-2 mb-2">
                    <input asp-for="Title" class="form-control" required />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group col-4">

                <div class="row-4 mb-2">
                    <label asp-for="Date"></label>
                </div>
            </div>
            <div class="form-group col-8">

                <div class=" row-2 mb-2">
                    <input asp-for="Date" class="form-control" required/>
                    <span asp-validation-for="Date" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group col-4">

                <div class="row-4 mb-2">
                    <label asp-for="Location"></label>
                </div>
            </div>
            <div class="form-group col-8">
                <div class=" row-2 mb-2">
                    <input asp-for="Location" class="form-control" required/>
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group col-4">
                <div class="row-4 mb-2">
                    <label asp-for="StartTime"></label>
                </div>
            </div>
            <div class="form-group col-8">
                <div class=" row-2 mb-2">
                    <input asp-for="StartTime" class="form-control" required/>
                    <span asp-validation-for="StartTime" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group col-4">

                <div class="row-4 mb-2">
                    <label asp-for="Type"> </label>
                </div>
            </div>
            <div class="form-group col-8">
                <div class=" row-2 mb-2">
                    <input asp-for="Type" class="form-control" required />
                    <span asp-validation-for="Type" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group col-4">

                <div class="row-4 mb-2">
                    <label asp-for="Duration"></label>
                </div>
            </div>
            <div class="form-group col-8">
                <div class=" row-2 mb-2">
                    <input asp-for="Duration" class="form-control" />
                </div>
            </div>

            <div class="form-group col-4">

                <div class="row-4 mb-2">
                    <label asp-for="Description"></label>
                </div>
            </div>
            <div class="form-group col-8">
                <div class=" row-2 mb-2">
                    <input asp-for="Description" class="form-control" />
                </div>
            </div>

            <div class="form-group col-4">

                <div class="row-4 mb-2">
                    <label asp-for="OtherDetails"></label>
                </div>
            </div>
            <div class="form-group col-8">
                <div class=" row-2 mb-2">
                    <input asp-for="OtherDetails" class="form-control" />
                </div>
            </div>

            <div class="form-group col-4">

                <div class="row-4 mb-2">
                    <label asp-for="Invite"></label>
                </div>
            </div>
            <div class="form-group col-8">
                <div class=" row-2 mb-2">
                    <input asp-for="Invite" class="form-control" />
                </div>

                <div class="invisible row-2 mb-2">
                    <input asp-for="Userid" value="@User.Identity.Name" class="form-control" />
                </div>
            </div>

            <div class="form-group row">
                <div class="col-8 text-center row">
                    <div class="col">
                        <input type="submit" class="btn btn-info w-100 mb-4" value="Create" />
                    </div>

                    <div class="col">
                        <a asp-controller="Event" asp-action="Index" class="btn btn-danger w-100">Go Back</a>
                    </div>

                </div>
            </div>
        </div>
        </div>

</form>

MVC/MVC/Views/Event/Details.cshtml
@model MVC.Models.Event

        <div class="border p-3">
            <div class="form-group row">
                <h2 class="text-black-50 pl-3">Details of the Event </h2>
            </div>


            <div class="form-group row">
                <div class="col-8 text-center row">

                    <div class="row">
                        <!--<div class="col-6">-->
                        <div class="form-group col-4">
                            <div class="row-4 mb-2">
                                <label asp-for="Title"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Title" class="form-control" readonly/>
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Date"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">

                            <div class=" row-2 mb-2">
                                <input asp-for="Date" class="form-control" readonly/>
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Location"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Location" class="form-control" readonly />
                            </div>
                        </div>

                        <div class="form-group col-4">
                            <div class="row-4 mb-2">
                                <label asp-for="StartTime"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="StartTime" class="form-control" readonly />
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Type"> </label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Type" class="form-control" readonly />
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Duration"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Duration" class="form-control" readonly />
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Description"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Description" class="form-control" readonly />
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="OtherDetails"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="OtherDetails" class="form-control" readonly />
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Invite"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Invite" class="form-control" readonly/>
                            </div>

                        </div>


                        <div class="col">
                            <a asp-controller="Event" asp-action="Index" class="btn btn-danger w-50">Go Back</a>
                        </div>

                    </div>
                </div>
            </div>
        </div>

MVC/MVC/Views/Event/Index.cshtml
@model IEnumerable<MVC.Models.Event>
@using Microsoft.AspNetCore.Identity

@inject Microsoft.AspNetCore.Identity.SignInManager<IdentityUser> _signInManager


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Events List</h2>
        </div>
        <div class=" col-6 text-right">
            <a asp-controller="Event" asp-action="Create" class="btn btn-primary">Create new Event</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class=" table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Title
                    </th>
                    <th>
                        Date
                    </th>
                    <th>
                        Location
                    </th>
                    
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    @if (_signInManager.IsSignedIn(User) == false && (item.Type == "private"|| item.Type == "Private"))
                        continue;
                    else
                    {
                        <tr>
                            <td width="10%">@item.Title</td>
                            <td width="10%">@item.Date</td>
                            <td width="10%">@item.Location</td>
                            
                            <td width="10%">
                                <div class=" col-6 text-right">
                                    <a asp-controller="Event" asp-action="Update" asp-route-title="@item.Title" class="btn btn-primary">Update</a>
                                </div>
                                <div class=" col-6 text-right">
                                    <a asp-controller="Event" asp-action="Details" asp-route-title="@item.Title" class="btn btn-primary">Details</a>
                                </div>
                            </td>

                        </tr>
                    }
                 }
            </tbody>
        </table>

    }

    else
    {
        <p>No Event Created Yet</p>
    }
</div>

MVC/MVC/Views/Event/Update.cshtml
@model MVC.Models.Event

<form method="post" asp-action="Update">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Event </h2>
        </div>
        

            <div class="form-group row">
                <div class="col-8 text-center row">
                    
                    <div class="row">
                        <!--<div class="col-6">-->
                        <div class="form-group col-4">
                            <div class="row-4 mb-2">
                                <label asp-for="Title"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Title" class="form-control" required/>
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Date"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">

                            <div class=" row-2 mb-2">
                                <input asp-for="Date" class="form-control" required/>
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Location"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Location" class="form-control" required/>
                            </div>
                        </div>

                        <div class="form-group col-4">
                            <div class="row-4 mb-2">
                                <label asp-for="StartTime"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="StartTime" class="form-control" required/>
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Type"> </label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Type" class="form-control" required/>
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Duration"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Duration" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Description"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Description" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="OtherDetails"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="OtherDetails" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group col-4">

                            <div class="row-4 mb-2">
                                <label asp-for="Invite"></label>
                            </div>
                        </div>
                        <div class="form-group col-8">
                            <div class=" row-2 mb-2">
                                <input asp-for="Invite" class="form-control" />
                            </div>

                        </div>

                        <div class="col">
                            <input type="submit" class="btn btn-info w-100 mb-4" value="Update" />
                        </div>

                        <div class="col">
                            <a asp-controller="Event" asp-action="Index" class="btn btn-danger w-100">Go Back</a>
                        </div>

                    </div>
                </div>
        </div>
    </div>

</form>

MVC/MVC/Views/Home/Index.cshtml
@model IEnumerable<MVC.Models.Event>

@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Events Invited To</title>
</head>
<body>
    <div class="text-center">
        <h1 class="display-4">Welcome</h1>
    </div>

    <div class="table-responsive">
        <table class="mx-5 table-striped mt-8" style="width:65%" >
            <thead>
                <tr>
                    <th>
                        Past Events
                    </th>
                    <th>
                        Future Events
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    @if (item.Type == "Public" || item.Type == "public")
                    {
                        <tr>
                            @{DateTime target = item.Date;}
                            @{DateTime today = DateTime.Today;}

                            @if (target < today)
                            {
                                <td><a asp-controller="Event" asp-action="Details" asp-route-title="@item.Title"> @item.Title </a></td>
                            }
                            else
                            {
                                <td></td>
                                <td><a asp-controller="Event" asp-action="Details" asp-route-title="@item.Title"> @item.Title </a></td>
                            }
                        </tr>

                    }
                }
            </tbody>
        </table>
    </div>
</body>
</html>

MVC/MVC/Views/InvitedTo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<MVC.Models.Event>
@using Microsoft.AspNetCore.Identity
@inject Microsoft.AspNetCore.Identity.SignInManager<IdentityUser> _signInManager

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <meta name="viewport" content="width=device-width" />
    <title>Events Invited To</title>
</head>
<body>
    <div class="text-center">
        <h2 class="text-primary mt-4">Events Invited To</h2>
    </div>
    <div class="list-group align-items-md-center">
        @foreach (var item in Model)
        {
            <ol>
                @if (User.Identity.Name == item.Invite)
                {
                    <li><a asp-controller="Event" asp-action="Index"> @item.Title </a></li>
                }
            </ol>
        }

    </div>

</body>
</html>

MVC/MVC/Views/MyEvents/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
@model IEnumerable<MVC.Models.Event>
@using Microsoft.AspNetCore.Identity
@inject Microsoft.AspNetCore.Identity.SignInManager<IdentityUser> _signInManager

<!DOCTYPE html>

<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <meta name="viewport" content="width=device-width" />
    <title>My Events </title>
</head>
<body>
    <div class="text-center">
        <h2 class="text-primary mt-4">My Events (created by me)</h2>
    </div>
    <div class="list-group align-items-md-center">
        @foreach (var item in Model)
        {
            <ol>
                @if (User.Identity.Name == item.Userid)
                {
                    <li>
                        <a asp-controller="Event" asp-action="Index"> @item.Title </a>

                        <a asp-controller="Event" asp-action="Update" asp-route-title="@item.Title" class="btn btn-info btn-sm ml-3 pl-3">Update</a>

                    </li>
                }
            </ol>
        }

    </div>

</body>
</html>